apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gj4et1kp8-java-quarkus
  janus-idp.io/tekton: gj4et1kp8-java-quarkus
  backstage.io/kubernetes-id: gj4et1kp8-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gj4et1kp8-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
